### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by webbertakken** [mob-sakai/unity-changeset#13]
At GameCI we're working on a Deno based CLI. Most dependencies are portable but not unity-changeset yet.

**Describe the solution you'd like**
It would be great if this dependency could be published at https://deno.land/x as well

**Describe alternatives you've considered**
We could also manually port it, but it would be harder to maintain

**Additional context**
Deno support mostly just requires you to use different imports.
There seem to be tools that compile for Deno target as well.

**Comment by mob-sakai** [comment]
@webbertakken 
I've never used deno, but from what I understand:
- Rewrite the project, to a deno based project.
- Rewire the dependencies, using import maps.
- I can use `dnt`, to convert to npm packages.

right?

**Comment by webbertakken** [comment]
As far as I understand, yes.

**Comment by mob-sakai** [comment]
WIP:
Working on the `develop` branch.
So far it is not working well...

**Comment by mob-sakai** [comment]
@webbertakken 
Version 2.0.0 with deno support has been released. 👍 
https://deno.land/x/unity_changeset@2.0.0/src

**Comment by webbertakken** [comment]
Amazing. Thank you very much!
