### ISSUE TITLE
--lts returns no version

### ISSUE THREAD

**Issue by RedGlow** [mob-sakai/unity-changeset#17]
**Describe the bug**
Latest (2.3.0) version of unity-changeset, used as a command line, returns nothing with the --lts flag.

**To Reproduce**
1. Run the command:
```sh
npx unity-changeset@2.3.0 list --lts
```
2. The command outputs nothing.

**Expected behavior**
It should output all the LTS versions.

**Environment:**
 - OS: Windows 11
 - Node: 20.10.0
 - Npm: 9.2.0
 - Version: 2.3.0

**Additional context**
Running the same command without the --lts flag correctly prints all the versions:
```
> npx unity-changeset@2.3.0 list
6000.0.31f1     a206c360e2a8
6000.0.30f1     62b05ba0686a
6000.0.29f1     9fafe5c9db65
6000.0.28f1     f336aca0cab5
6000.0.27f1     27c554a2199c
6000.0.26f1     ccb7c73d2c02
6000.0.25f1     4859ab7b5a49
6000.0.24f1     11fa355cd605
6000.0.23f1     1c4764c07fb4
...
```

**Comment by mob-sakai** [comment]
Thank you for your reporting!
