### ISSUE TITLE
Version 1.4.3 is broken

### ISSUE THREAD

**Issue by aurelien-lbc** [mob-sakai/unity-changeset#6]
Version 1.4.3 gives the following error.
`Cannot find module '../dist/index'`
Version 1.4.2 works fine with 
`npx unity-changeset@1.4.2 list`

**Comment by mob-sakai** [comment]
@aurelien-lbc 
Thank you for your reporting!

The release workflow was broken.
Now, `v1.4.5` works correctly! 😄
