### ISSUE TITLE
feature request: GitHub Action for this awesome feature

### ISSUE THREAD

**Issue by SimonDarksideJ** [mob-sakai/unity-changeset#8]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Is your feature request related to a problem? Please describe.**

Love the tool, but it would also be fantastic if it was published to the GitHub actions marketplace as a GitHub action

Keep up the great work

**Comment by mob-sakai** [comment]
@SimonDarksideJ 
Thank you for your feature request.
How are you thinking about how to use it?

**Comment by SimonDarksideJ** [comment]
Exactly the way you would in NPM.

I've several pipelines which need to install a specific version of Unity, which requires you to have the changeset id for that version.

I have some workaround powershell, but it would be better to use a marketplace action to just "do it for me" :D

**Comment by mob-sakai** [comment]
Please try this 👍 
https://github.com/marketplace/actions/unity-changeset
